---
  - name: Create Script directory
    ansible.windows.win_file:
      path: c:\Script
      state: directory

  - name: Run Script
    script: files/manage-computerobjects.ps1
    args:
      creates: C:\Script\Script-import.txt