---
#####################################
### Move ad objects
#####################################

#  - name: Create Script directory
#    ansible.windows.win_file:
#      path: c:\Script
#      state: directory

#  - name: Run Script
#    script: files/manage-computerobjects.ps1
#    args:
#      creates: C:\Script\Script-import.txt

- name: Create Log Folder
  win_file:
    path: C:\Logs
    state: directory

- name: Create variables
  script: create-variables.ps1
  args:
    creates: 
      - C:\Logs\create-variables.xml
      - C:\Logs\create-variables-plain.txt
  environment:
    dc_computer_objects: "{{ dc_computer_objects }}"

- name: Manage Computerobjects
  script: files/manage-computerobjects.ps1
