---
#####################################
### Move ad objects
#####################################

#  - name: Create Script directory
#    ansible.windows.win_file:
#      path: c:\Script
#      state: directory

#  - name: Run Script
#    script: files/manage-computerobjects.ps1
#    args:
#      creates: C:\Script\Script-import.txt

#- name: Move ad objects
#  microsoft.ad.object:
#    name: citrix-ctrl-01
#    path: OU=02_Administration,OU=Computer,OU=Objects,DC=dt,DC=democloud
#    type: computer
#    state: present

- name: move computer account to correct OU
  win_domain_computer:
    name: citrix-ctrl-01
    dns_hostname: citrix-ctrl-01.dt.democloud
    domain_username: dt\vagrant
    domain_password: vagrant
    # domain_server: "{{ domain }}"
    ou: OU=02_Administration,OU=Computer,OU=Objects,DC=dt,DC=democloud